version: '3.1'

services:

  news-db:
    container_name: news-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-example}
      POSTGRES_DB: ${DB_NAME:-news}
    ports:
      - "5432:5432"
    networks:
      - news-network

  news-app:
    container_name: news-app
    build:
      context: .
      dockerfile: Dockerfile
    image: news-app-image:latest
    environment:
      DB_HOST: ${DB_HOST:-news-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-news}
      DB_USERNAME: ${DB_USERNAME:-user}
      DB_PASSWORD: ${DB_PASSWORD:-example}
    depends_on:
      - news-db
    ports:
      - "8080:8080"
    networks:
      - news-network

networks:
  news-network:
    driver: bridge