spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:migrations/changelog.yaml
    drop-first: true

application:
  jwt:
    secret-key: ${JWT_SECRET_KEY:556A586E3272357538782F413F4428472B4B6150645367566B59703373367639}
    expiration: ${JWT_EXPIRATION:7200000}
